### ISSUE TITLE
add GPL License doc to root of *-api repos

### ISSUE THREAD

**Issue by springframeworkguru** [sfg-beer-works/sfg-beer-works#62]
Missing and not showing proper information on GitHub org page

**Comment by dfcoffin** [comment]
I've replaced the original MIT License files in all but the pub-api repository, but it appears the pub-api repository has only been created as a place holder.  Should I add the GPL License so this issue can be closed?

**Comment by springframeworkguru** [comment]
yeah - add one there too. I'll be creating the OA3 spec soon!

**Comment by dfcoffin** [comment]
Since the addition is done by creating a LICENSE file either when the repository is created or after files are present using GitHub to directly update the specific branch, it will be quicker to wait for you to do the initial repo load.

**Comment by springframeworkguru** [comment]
added to pub-api
